### ISSUE TITLE
Need url parameter rather than destination.

### ISSUE THREAD

**Issue by ghost** [rubycas/rubycas-client-rails#1]
When I use RubyCAS::Filter.logout(self) it redirect to https://example.com/cas/logout?destination=http://localhost:3000/customers but I need redirect to  https://example.com/cas/logout?url=http://localhost:3000/customers, my cas server use url and not destination as parameter.

**Comment by Jimflip** [comment]
Which CAS server are you using?

It seems that different servers use different param names for the redirect url:

RubyCAS -> 'destination'
JASIG -> 'service'

I think the correct param name is 'url' but with so many different ones in use perhaps it would be better to have it configurable on the client.

**Comment by Micka33** [comment]
I have the same problem, using JASIG, the param name should `service`.
How can I change it ?

**Comment by elspethsoup** [comment]
use the `cas_destination_logout_param_name` parameter when configuring the cas client.
