### ISSUE TITLE
uninitialized constant CGI::Session

### ISSUE THREAD

**Issue by javache** [rubycas/rubycas-client-rails#3]
When using the single-sign-out, I got the following error: NameError: uninitialized constant CGI::Session in  /var/lib/gems/1.9.1/bundler/gems/rubycas-client-rails-cec213ae2fbe/lib/rubycas-client-rails.rb:307:in `rescue in single_sign_out'

```
/var/lib/gems/1.9.1/bundler/gems/rubycas-client-rails-cec213ae2fbe/lib/rubycas-client-   rails.rb:307:in `rescue in single_sign_out'
/var/lib/gems/1.9.1/bundler/gems/rubycas-client-rails-cec213ae2fbe/lib/rubycas-client-   rails.rb:302:in `single_sign_out'
/var/lib/gems/1.9.1/bundler/gems/rubycas-client-rails-cec213ae2fbe/lib/rubycas-client-   rails.rb:43:in `filter'
activesupport (3.1.0.rc5) lib/active_support/callbacks.rb:313:in `before'
activesupport (3.1.0.rc5) lib/active_support/callbacks.rb:302:in `_callback_before_128'
activesupport (3.1.0.rc5) lib/active_support/callbacks.rb:412:in    `_run__4274737423150550086__process_action__3721162684752423431__callbacks'
activesupport (3.1.0.rc5) lib/active_support/callbacks.rb:386:in    `_run_process_action_callbacks'
activesupport (3.1.0.rc5) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.1.0.rc5) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.1.0.rc5) lib/action_controller/metal/rescue.rb:17:in `process_action'
actionpack (3.1.0.rc5) lib/action_controller/metal/instrumentation.rb:30:in `block in    process_action'
activesupport (3.1.0.rc5) lib/active_support/notifications.rb:55:in `block in instrument'
activesupport (3.1.0.rc5) lib/active_support/notifications/instrumenter.rb:21:in    `instrument'
activesupport (3.1.0.rc5) lib/active_support/notifications.rb:55:in `instrument'
actionpack (3.1.0.rc5) lib/action_controller/metal/instrumentation.rb:29:in    `process_action'
actionpack (3.1.0.rc5) lib/action_controller/metal/params_wrapper.rb:202:in    `process_action'
activerecord (3.1.0.rc5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
```

**Comment by Jimflip** [comment]
I'm getting this also using rails 3.0.8

**Comment by Jimflip** [comment]
This issue is already raised in rubycas-client along a patch which hasn't been applied.

The root of the problem is that rails can't stick to an identifier and leave it the fook alone :)

In rails3 not sure from which version we need the following

current_sess_store = ::Rails.application.config.session_store

which will probably also change at some point..perhaps it would be wise to put a catch around the whole block, and if an exception is raised some useful debug explaining the joys of Rails development.

**Comment by javache** [comment]
Hi @Jimflip, 

I fixed most of these issues in my own fork of this gem: https://github.com/Javache/rubycas-client-rails
(maybe I should add a pull request...)

**Comment by Jimflip** [comment]
Hi @Javache 

Might as well put in a pull request, there don't seem to be too many issues outstanding, lets try and get a new release.

**Comment by zuk** [comment]
Okay I think 3924f4e    should have dealt with this. Please reopen if the problem persists.
