### ISSUE TITLE
Single Sign Out request requires URI decode

### ISSUE THREAD

**Issue by bryanlarsen** [rubycas/rubycas-client-rails#8]
Single Sign Out functionality does not currently work for me.   I traced one of the problems to the regexp in RubyCas::Filter#single_sign_out.   To get things to work I had to add `URI.unescape` to the left side of the =~.

pull request to follow

**Comment by zuk** [comment]
The problem might be that the SSOut request shouldn't be getting URI.escaped by the server in the first place. I'll have to look on the other end to see why it's being escaped, and whether we can disable that.

**Comment by bryanlarsen** [comment]
sorry, accidentally created another issue for the pull request.
